version: '2.2'
services:
  heartbeat:
    container_name: heartbeat
    hostname: heartbeat
    user: root #To read the docker socket
    image: "docker.elastic.co/beats/heartbeat:7.10.0"
    volumes:
      #Mount the Heartbeat configuration so users can make edits.
      - ${PWD}/config/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      elasticsearch: { condition: service_healthy }
    command: heartbeat -e -strict.perms=false
networks:
  host:
    external: true
