version: "3.3"

services:

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.10.0
    hostname: metricbeat-laptop
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - metricbeat:/usr/share/metricbeat/data
      - ${PWD}/config/metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      - ELASTICSEARCH_HOST="http://es01:9200"
      - KIBANA_HOST="http://kibana:5601"
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
#    deploy:
#      mode: global

networks:
#  elk_default:
#    external: true
  host:
    external: true
    # https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host
 

volumes:
  metricbeat: